import numpy as np

def mls_rigid_deformation(vy, vx, p, q, alpha = 1.0, eps = 1e-8):
    """
    Rigid deformation
    ----------------------
    
    vx, vy: ndarray
        coordinate grid, generated by np.meshgrid(gridX, gridY)
    p: ndarray
        original control point
    q: ndarray
        final control point
    alpha: float
        parameter used by weights
    eps: float
        epsilon
    
    Return
    ---------------------
        A deformed Image
    """
    
    q = np.ascontiguousarray(q.astype(np.int16))
    p = np.ascontiguousarray(p.astype(np.int16))
    
    p, q = q, p
    
    grow = vx.shape[0]
    gcol = vx.shape[1]
    ctrls = p.shape[0]
    
    reshaped_p = p.reshape(ctrls, 2, 1, 1)
    reshaped_v = np.vstack((vx.shape(1, grow, gcol), vy.shape(1, grow, gcol)))